spring.application.name=email-scheduler

spring.datasource.url=jdbc:postgresql://localhost:5432/emaildb
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update

spring.activemq.broker-url=${ACTIVEMQ_BROKER_URL:tcp://localhost:61616}
spring.activemq.user=${ACTIVEMQ_USER:admin}
spring.activemq.password=${ACTIVEMQ_PASSWORD:admin}
spring.activemq.pool.enabled=true
spring.activemq.pool.max-connections=2

activemq.queue.scheduled-emails=scheduled-emails.events

spring.mail.host=localhost
spring.mail.port=1025

email.from=noreply@emailscheduler.com
